indeedeng/iwf

docker-compose/docker-compose.yml
docker-compose/init.sh
script/start-server.sh

https://github.com/indeedeng/iwf/issues/74

Improve docker compose startup script

---

service/interpreter/activityImpl.go

example usage:
for worker URL: `http://localhost/:$PORT4$/iwf-samples/worker`
Then env for iWF-server: AUTO_FIX_WORKER_PORT_FROM_ENV=PORT4

Provide autofix for worker port

---

integ/conditional_close_test.go
integ/workflow/conditional_close/routers.go
service/interpreter/workflowImpl.go

For https://github.com/indeedeng/iwf/issues/291

Support Conditional close signal channel empty

---

CONTRIBUTING.md
README.md
docker-compose/init-ci-temporal.sh
docker-compose/init-compose.sh

for https://github.com/indeedeng/iwf/issues/313

Deprecate tctl in favor of new Temporal CLI

---

gen/iwfidl/api/openapi.yaml
gen/iwfidl/docs/TimerCommand.md
gen/iwfidl/model_timer_command.go
integ/timer_test.go
integ/workflow/any_command_combination/routers.go
integ/workflow/any_timer_signal/routers.go
integ/workflow/timer/routers.go
integ/workflow/wait_for_state_completion/routers.go
service/interpreter/timerProcessor.go
service/interpreter/workflowImpl.go

Use timer duration to replace firingTimestamp for timerCommand

---

lite/start-lite-server.sh

When I  try to use the [all in one docker image](https://github.com/indeedeng/iwf?tab=readme-ov-file#using-all-in-one-docker-image) I get these errors repeatedly
It looks like the script uses one `-` where there should be 2
see https://docs.temporal.io/cli/operator#create-1
```
Error: unknown shorthand flag: 't' in -type
Usage:
temporal operator search-attribute create [flags]
Flags:
-h, --help               help for create
--name stringArray   Search Attribute name.
--type stringArray   Search Attribute type. Accepted values: Text, Keyword, Int, Double, Bool, Datetime, KeywordList.
Global Flags:
--address string                                    Temporal server address. (default "127.0.0.1:7233")
--api-key string                                    Sets the API key on requests. …
```

fix temporal command line arguments

---

config/config.go
config/config_template.yaml
config/development.yaml
config/development_cadence.yaml
go.mod
integ/config.go
service/api/cadence/client.go
service/api/service.go
service/api/temporal/client.go
service/client/interfaces.go
service/common/utils/utils.go
service/interpreter/activityImpl.go
service/interpreter/cadence/workflowProvider.go
service/interpreter/interfaces.go
service/interpreter/temporal/workflowProvider.go
service/interpreter/workflowImpl.go

IWF-132: Use firstRunId instead workflowId when naming WaitForStateExecutionCompletion workflow

---

integ/wait_until_search_attributes_optimization_test.go
integ/workflow/wait_until_search_attributes_optimization/routers.go
replayTests/history/v6-search-attributes-optimization.json
replayTests/replay_test.go
service/api/cadence/client.go
service/api/temporal/client.go
service/client/interfaces.go
service/interpreter/stateExecutionCounter.go
service/interpreter/workflowImpl.go

IWF-208: Optimize executingStateIdMode for state transition

---

CONTRIBUTING.md

Because we have use JAR file for open API generator for pinning the version
Closes #issue_number

Update CONTRIBUTING.md to remove the brew commands that no longer needed

---

service/interpreter/cadence/worker.go
service/interpreter/temporal/worker.go

IWF-233: Override WorkerOptions default values

---

integ/wait_until_search_attributes_optimization_test.go
replayTests/history/v7-no-global-version-search-attribute.json
replayTests/replay_test.go
service/interpreter/globalVersioner.go
service/interpreter/workflowImpl.go

IWF-141: Disable global version search attribute

---

integ/conditional_close_test.go
integ/workflow/conditional_close/routers.go
replayTests/history/v8-yield-on-conditional-complete.json
replayTests/replay_test.go
service/interpreter/globalVersioner.go
service/interpreter/signalReceiver.go
service/interpreter/workflowImpl.go

IWF-364: Fix conditional complete on messages of internalChannels from state APIs

---

cmd/server/iwf/iwf.go
config/config.go
config/config_template.yaml
config/development.yaml
config/development_cadence.yaml
integ/config.go
integ/create_test.go
integ/signal_test.go
integ/timer_test.go
integ/util.go
service/client/cadence/client.go
service/client/temporal/client.go
service/client/temporal/client_test.go

IWF-163: Add retry policy to QueryWorkflow calls

---

service/api/handler.go
service/common/log/truncate.go
service/interpreter/activityImpl.go

IWF-415: Improve activity logging

---

gen/iwfidl/api/openapi.yaml
gen/iwfidl/docs/EventType.md
gen/iwfidl/docs/IwfEvent.md
gen/iwfidl/model_event_type.go
gen/iwfidl/model_iwf_event.go
service/api/service.go
service/interpreter/workflowUpdater.go

IWF-410: emit RCP_EXECUTION_EVENT

---

integ/reset_by_state_id_test.go
integ/workflow/reset/routers.go
service/client/cadence/reset.go
service/client/temporal/reset.go

iwf-401: update activity type name to find reset history eventID

---

integ/internalchannel_test.go
integ/locking_test.go
integ/wf_state_execute_api_fail_and_proceed_test.go
integ/wf_state_wait_until_api_fail_and_proceed_test.go
service/interpreter/outputCollector.go

IWF-124: Ignore empty output for collector

---

docker-compose/ci-cadence-dependencies.yml
docker-compose/ci-cadence-temporal-dependencies.yml
docker-compose/integ-dependencies.yml
service/interpreter/globalVersioner.go

Merge code freeze changes

---

integ/workflow/any_command_close/routers.go
integ/workflow/any_command_combination/routers.go
integ/workflow/any_timer_signal/routers.go
integ/workflow/basic/routers.go
integ/workflow/conditional_close/routers.go
integ/workflow/deadend/routers.go
integ/workflow/headers/routers.go
integ/workflow/interstate/routers.go
integ/workflow/locking/routers.go
integ/workflow/parallel/routers.go
integ/workflow/persistence/routers.go
integ/workflow/persistence_loading_policy/routers.go
integ/workflow/rpc/routers.go
integ/workflow/signal/routers.go
integ/workflow/skipstart/routers.go
integ/workflow/timer/routers.go
integ/workflow/wait_for_state_completion/routers.go
integ/workflow/wait_until_search_attributes/routers.go
integ/workflow/wait_until_search_attributes_optimization/routers.go
integ/workflow/wf_execute_api_fail_and_proceed/routers.go
integ/workflow/wf_force_fail/routers.go
integ/workflow/wf_state_api_fail/routers.go
integ/workflow/wf_state_api_fail_and_proceed/routers.go
integ/workflow/wf_state_api_timeout/routers.go
integ/workflow/wf_state_options_data_attributes_loading/routers.go
integ/workflow/wf_state_options_search_attributes_loading/routers.go

IWF-439: Add comments for integration test workflows

---

gen/iwfidl/api/openapi.yaml
gen/iwfidl/docs/IwfEvent.md
gen/iwfidl/model_iwf_event.go
service/api/service.go
service/interpreter/activityImpl.go
service/interpreter/workflowImpl.go
service/interpreter/workflowUpdater.go

IWF-546: Add search attributes to IwfEvents

---

integ/persistence_loading_policy_test.go
integ/set_data_attributes_test.go
integ/set_search_attributes_test.go
integ/start_with_no_options_test.go
integ/wf_state_options_data_attributes_loading_test.go
integ/wf_state_options_search_attributes_loading_test.go

IWF-532: Close integration test workflows when finished

---

service/api/service.go
service/interpreter/activityImpl.go
service/interpreter/workflowImpl.go
service/interpreter/workflowUpdater.go

IWF-512: Add start timestamp field to all events

---

.gitignore
service/interpreter/timers/greedyTimerScheduler.go
service/interpreter/timers/greedyTimerScheduler_test.go

IWF-1053: Fix greedy timer scheduler workflow cancelation bug

---

lite/Dockerfile
lite/start-lite-server.sh

IWF-1115: adding S3 storeage for lite server
