indeedeng/iwf

.gitmodules, gen/iwfidl/api/openapi.yaml, gen/iwfidl/docs/WorkflowGetSearchAttributesResponse.md, gen/iwfidl/model_workflow_get_search_attributes_response.go, integ/attribute_test.go, service/api/cadence/client.go, service/api/handler.go, service/api/interfaces.go, service/api/routers.go, service/api/service.go, service/api/temporal/client.go
temporal tested
cadence tested
=> add getSearchAttribute

integ/basic_test.go, service/api/cadence/client.go, service/api/interfaces.go, service/api/service.go, service/api/temporal/client.go, service/const.go
=> Adding back CronSchedule and IdReusePolicy to StartWorkflowOptions

CONTRIBUTING.md, service/interpreter/workflowImpl.go
https://github.com/uber-go/cadence-client/issues/1198
=> Bug fix: workaround cadence client bug of concurrent map writes

README.md, service/const.go, service/interpreter/InterStateChannel.go, service/interpreter/continue_as_new.go, service/interpreter/workflowImpl.go
For https://github.com/indeedeng/iwf/issues/107
=> Auto ContinueAsNew part 2-1: Implement query handler for interStateChannel

script/start-server.sh
=> fix(script): correct typos in start-server.sh

service/interfaces.go, service/interpreter/continueAsNewer.go, service/interpreter/workflowImpl.go
=> AutoContinueAsNew: dump dataObjects and search attributes in query

.github/workflows/ci-temporal-integ-test.yml, Makefile, README.md
for https://github.com/avelino/awesome-go/pull/4749
=> Use codecov for coverage report

README.md, script/http/local/home.http
for https://github.com/indeedeng/iwf/issues/189
=> Add doc about workflow options and workflow state options

integ/history/v1-persistence.json, integ/history/v2-basic.json, integ/history/v2-persistence.json, integ/persistence_test.go, integ/replay_test.go, service/api/service.go, service/common/mapper/searchAttribute.go, service/interpreter/globalVersionProvider.go, service/interpreter/stateExecutionCounter.go, service/interpreter/workflowImpl.go
for https://github.com/indeedeng/iwf/issues/206
=> Optimize upsert system search attributes for StateId and IwfWorkflowType

docker-compose/init-ci-temporal.sh, integ/main_test.go
for https://github.com/temporalio/temporal/issues/4160
=> Workaround temporal search attribute registration issue

integ/deadend_test.go, integ/history/v3-bug-no-state-stuck.json, integ/history/v4-continue-as-new-on-no-state.json, integ/replay_test.go, integ/workflow/deadend/routers.go, service/interpreter/globalVersioner.go, service/interpreter/workflowImpl.go
TODO: new test case + replay test
=> Fix continueAsNew for non-states workflow

integ/persistence_loading_policy_test.go, integ/workflow/persistence_loading_policy/routers.go, service/api/service.go
This MR did:
- correctly return the loaded attributes with RPC memo
=> Fix the loaded attributes with PRC memo

gen/iwfidl/api/openapi.yaml, gen/iwfidl/docs/TimerCommand.md, gen/iwfidl/docs/WorkflowStartRequest.md, gen/iwfidl/docs/WorkflowStateDecideResponse.md, gen/iwfidl/docs/WorkflowStateStartResponse.md, gen/iwfidl/model_timer_command.go, gen/iwfidl/model_workflow_start_request.go, gen/iwfidl/model_workflow_state_decide_response.go, gen/iwfidl/model_workflow_state_start_response.go, integ/wait_for_state_completion_test.go, integ/workflow/timer/routers.go, script/http/local/home.http, service/api/service.go, service/interfaces.go, service/interpreter/activityImpl.go, service/interpreter/workflowImpl.go
for https://github.com/indeedeng/iwf/issues/406 and https://github.com/indeedeng/iwf/issues/403
=> Support WaitForCompletionStateIds and add local activity input debug

gen/iwfidl/api/openapi.yaml, gen/iwfidl/docs/IDReusePolicy.md, gen/iwfidl/model_id_reuse_policy.go, service/common/compatibility/workflowStartOptions.go
> Fix typo IdReusePolicy of ALLOW_IF_PREVIOUS_EXISTS_ABNORMALLY
=> IWF-106: Fix typo IdReusePolicy of ALLOW_IF_PREVIOUS_EXISTS_ABNORMALLY

replayTests/history/v5-basic.json, replayTests/replay_test.go, service/interpreter/globalVersioner.go, service/interpreter/versions/versions.go, service/interpreter/workflowImpl.go, service/interpreter/workflowUpdater.go
=> IWF-207: Add new version: StartingVersionTemporal26SDK

service/interpreter/cadence/workflowProvider.go, service/interpreter/workflowImpl.go
=> Use firstRunId for workflow context

config/config.go
Closes https://github.com/indeedeng/iwf/issues/461
=> Update config.go to fix typo in comments

integ/signal_test.go, service/api/service.go
=> IWF-228: returning 400 for missing workflowId

integ/signal_test.go
=> IWF-228: skipping cadence test

service/api/service.go, service/const.go
=> IWF-254: Override WorkflowConfig field by field

docker-compose/init-ci-temporal.sh, docker-compose/init-compose.sh, integ/set_search_attributes_test.go, integ/workflow/persistence/routers.go
=> IWF-324: adding keyword array to search attributes

service/common/rpc/invoke.go
=> IWF-397: Avoid passing nil in WorkflowWorkerRpcRequest

service/api/service.go
=> IWF-397: Remove memo optimization for RPC

service/interpreter/globalVersioner.go
=> IWF-247: Add global version comments

docker-compose/ci-cadence-dependencies.yml, docker-compose/ci-cadence-temporal-dependencies.yml, docker-compose/integ-dependencies.yml
=> Fix Cadence starting issue  in docker compose  

service/common/urlautofix/autofix.go
=> IWF-121 remove all trailing `/` from worker url

service/client/cadence/client.go, service/client/temporal/client.go
Draft PR for: Add error details to events emitted
=> IWF-567: Add error details to events emitted

integ/locking_test.go
=> IWF-533: Fix locking_test.go Integration Test

service/interpreter/continueAsNewer.go, service/interpreter/deciderTriggerer.go, service/interpreter/persistence.go, service/interpreter/stateExecutionCounter.go, service/interpreter/stateRequestQueue.go, service/interpreter/temporal/workflowProvider.go
Use DeterministicKeys for every map iteration in the interpreter
Closes #510
=> IWF-474: Use DeterministicKeys for every map iteration in the interpreter

integ/start_with_no_options_test.go, replayTests/history/v8-activity-for-sync-updates-rpcs.json, replayTests/history/v8-before-force-local-activity-for-sync-updates-rpcs.json, replayTests/history/v9-force-local-activity-for-sync-updates-rpcs.json, replayTests/replay_test.go, service/interpreter/cadence/workflowProvider.go, service/interpreter/globalVersioner.go, service/interpreter/interfaces/interfaces.go, service/interpreter/temporal/workflowProvider.go, service/interpreter/workflowUpdater.go
Always use local activity for synchronous update based RPC
Closes #522
=> IWF-481: Always use local activity for synchronous update based RPC

integ/large_data_attributes_test.go, integ/locking_test.go, integ/persistence_test.go, integ/rpc_test.go, integ/set_data_attributes_test.go, integ/workflow/locking/routers.go, integ/workflow/persistence/routers.go, integ/workflow/persistence_loading_policy/routers.go, integ/workflow/rpc/routers.go, integ/workflow/wf_state_options_data_attributes_loading/routers.go, integ/workflow/wf_state_options_search_attributes_loading/routers.go, service/api/handler.go, service/api/routers.go, service/api/service.go, service/common/compatibility/stateOptions.go, service/interpreter/continueAsNewer.go, service/interpreter/persistence.go, service/interpreter/queryHandler.go, service/interpreter/signalReceiver.go, service/interpreter/workflowImpl.go, service/interpreter/workflowUpdater.go
This is a draft MR
Closes #455
=> IWF-736: rename data objects to data attributes

README.md
Temporal team offers us a new badge to show case to help more people discover the iWF project. Also wanted to refresh some wording for summarize iWF and also new links to blog posts. 
Closes #issue_number
=> Update README for temporal badge and more links for community

integ/signal_test.go
=> IWF-774: Fix TestSignalWorkflowCadence test

cmd/server/iwf/iwf.go, integ/util.go, service/api/service.go, service/common/blobstore/interfaces.go, service/common/blobstore/store_impl.go
=> Refactor blobStore to support listing and delete S3 objects

integ/s3_wf_start_input_test.go, service/interpreter/activityImpl.go
=> refactor stateinput read/write logic

service/api/service.go
=> Fix NPE for start API with blobstore
